# Evaluate model performance with PR curves, confusion matrixes, and F1 scores

## Import libraries

In [1]:
import pathlib
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from joblib import load
from sklearn.metrics import precision_recall_curve, auc

sys.path.append("../../utils")
from eval_utils import (
    generate_confusion_matrix_df,
    generate_f1_score_df,
    generate_accuracy_score_df,
)
from training_utils import load_data, get_X_y_data

## Set paths to different datasets and models

In [2]:
# Directory with datasets
data_dir = pathlib.Path("../0.train_logistic_regression/data")

# Directory with models
models_dir = pathlib.Path("../0.train_logistic_regression/models")

# Path to encoder file
encoder_path = pathlib.Path("../0.train_logistic_regression/encoder_results/label_encoder_log_reg_fs_plate_4.joblib")

# Directory for model figures output
fig_dir = pathlib.Path("./figures")
fig_dir.mkdir(exist_ok=True)

# Directory for result outputs (accuracy scores)
results_dir = pathlib.Path("./results")
results_dir.mkdir(exist_ok=True)

# Load in each model individually
final_model = load(
    pathlib.Path(f"{models_dir}/log_reg_fs_plate_4_final_downsample.joblib")
)
shuffled_model = load(
    pathlib.Path(f"{models_dir}/log_reg_fs_plate_4_shuffled_downsample.joblib")
)

# List of data sets to apply models to
data_set_list = ["training", "testing", "holdout1", "holdout2"]

# Path to the CSV file containing indices for training data
training_indices_path = pathlib.Path("../0.train_logistic_regression/training_data_indices.csv")

## Precision-Recall Curves

### Output precision and recall data per dataset applied to each model and combine into one df

In [3]:
# Define the subdirectory for this plot type within fig_dir
pr_curves_dir = fig_dir / "pr_curves"
pr_curves_dir.mkdir(parents=True, exist_ok=True)  # Create subdirectory if it doesn't exist

# Initialize empty lists to store data for each iteration
precision_list = []
recall_list = []
threshold_list = []
model_type_list = []
data_type_list = []

for model_path in models_dir.iterdir():
    if model_path.is_dir() or model_path.suffix != ".joblib":
        continue  # Skip directories or files that are not model files

    print("Evaluating", model_path.stem.split("_")[5], "model...")
    
    for data_path in data_dir.iterdir():
        # Skip directories or files without the ".csv" suffix
        if data_path.is_dir() or data_path.suffix != ".csv":
            continue
        
        print("Applying model to", data_path.stem, "...")
        
        # Load the dataset as a dataframe
        df = pd.read_csv(data_path)

        # If this is training data, filter rows using the training indices
        if data_path.stem == "training_data":
            # Skip the header row when reading the CSV
            training_indices = pd.read_csv(training_indices_path, header=0).iloc[:, 0].tolist()

            # Convert to integers to ensure compatibility
            try:
                training_indices = [int(idx) for idx in training_indices]
            except ValueError as e:
                print("Error parsing indices:", e)
                raise

            # Use .iloc if training_indices are row positions
            df = df.iloc[training_indices]

        # Extract X and y using the updated function
        X, y = get_X_y_data(df=df, label="Metadata_cell_type")

        # Load in model to apply to datasets
        model = load(model_path)

        # Load in label encoder
        le = load(encoder_path)

        # Assign y classes to correct binary using label encoder results
        y_binary = le.transform(y)

        # Predict class probabilities for morphology feature data
        predicted_probs = model.predict_proba(X)

        # For binary classification, ensure you're getting the probabilities for the positive class
        if predicted_probs.shape[1] == 2:  # Binary classification
            positive_class_probs = predicted_probs[:, 1]  # Select the probability for the positive class
        else:  # Multi-class classification
            # Choose the probability for the class you're interested in (usually the last one)
            positive_class_probs = predicted_probs[:, -1]

        # Calculate the precision, recall data
        precision, recall, threshold = precision_recall_curve(
            y_binary, positive_class_probs
        )
        threshold = np.append(threshold, np.nan)

        # Append data to lists
        precision_list.extend(precision.tolist())
        recall_list.extend(recall.tolist())
        threshold_list.extend(threshold.tolist())
        model_type_list.extend([model_path.stem.split("_")[5]] * len(precision))
        data_type_list.extend([data_path.stem.split("_")[0]] * len(precision))

# Create a DataFrame from the accumulated data
pr_df = pd.DataFrame(
    {
        "Precision": precision_list,
        "Recall": recall_list,
        "Threshold": threshold_list,
        "Model_Type": model_type_list,
        "Data_Type": data_type_list,
    }
)

# Drop any NA data
pr_df.dropna(inplace=True)

# Show output of all data
print(pr_df.shape)
pr_df.head()

Evaluating final model...
Applying model to training_data ...
Applying model to holdout2_data ...
Applying model to holdout1_data ...

/tmp/ipykernel_4150415/178324479.py:26: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

Applying model to testing_data ...
Evaluating shuffled model...
Applying model to training_data ...
Applying model to holdout2_data ...
Applying model to holdout1_data ...

/tmp/ipykernel_4150415/178324479.py:26: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path)

Applying model to testing_data ...
(29368, 5)

   Precision  Recall     Threshold Model_Type Data_Type
0   0.500000     1.0  2.624497e-07      final  training
1   0.500077     1.0  9.720967e-07      final  training
2   0.500154     1.0  1.418125e-06      final  training
3   0.500231     1.0  2.128856e-06      final  training
4   0.500308     1.0  2.360339e-06      final  training

### Plot precision-recall curves for training and testing data per model type

In [4]:
# PR curves with only testing and training data
plt.figure(figsize=(12, 8))
sns.set_style("whitegrid")

# Filter data frame to only show training versus testing
filtered_df = pr_df[pr_df["Data_Type"].isin(["training", "testing"])]

# Define color for data splits
colors = {"training": "#D55E00", "testing": "#009E73"}

sns.lineplot(
    x="Recall",
    y="Precision",
    hue="Data_Type",
    style="Model_Type",
    dashes={"final": (1, 0), "shuffled": (2, 2)},
    palette=colors,
    data=filtered_df,
    linewidth=4,  # Adjust the line width as needed
)

# Set legend location
plt.legend(loc='lower right')

plt.ylim(bottom=0.0, top=1.02)
plt.xlabel("Recall", fontsize=24)
plt.ylabel("Precision", fontsize=24)
plt.title("Precision vs. Recall Plate 4 Cell Type Classification", fontsize=18)

# Adjust x-axis ticks font size
plt.xticks(fontsize=20)

# Adjust y-axis ticks font size and labels
plt.yticks(fontsize=20)

plt.tight_layout()
plt.savefig(f"{pr_curves_dir}/precision_recall_plate4_downsample.pdf", dpi=500, bbox_inches='tight')

# Avoid showing plot in notebook
plt.close()

### Plot precision-recall curves for **training data only** per model type

In [5]:
# PR curves with only testing and training data
plt.figure(figsize=(12, 10))
sns.set_style("whitegrid")

# Filter data frame to only show training versus testing
filtered_df = pr_df[pr_df["Data_Type"].isin(["training"])]

# Define color for data split
colors = {"training": "#D55E00"}

sns.lineplot(
    x="Recall",
    y="Precision",
    hue="Data_Type",
    style="Model_Type",
    dashes={"final": (1, 0), "shuffled": (2, 2)},
    palette=colors,
    data=filtered_df,
    linewidth=2.5  # Adjust the line width as needed
)

plt.legend(loc="lower right", fontsize=15)
plt.ylim(bottom=0.0, top=1.02)
plt.xlabel("Recall", fontsize=18)
plt.ylabel("Precision", fontsize=18)
plt.title("Precision vs. Recall Plate 4 Training Only", fontsize=18)

# Adjust x-axis ticks font size
plt.xticks(fontsize=14)

# Adjust y-axis ticks font size and labels
plt.yticks(fontsize=14)

plt.tight_layout()
plt.savefig(f"{pr_curves_dir}/precision_recall_plate4_downsample_only_training.png", dpi=500)

# Avoid showing plot in notebook
plt.close()

### Calculate Area Under the Precision Recall Curve (AUPRC) for the training and testing data (final model)

In [6]:
# Filter the dataframe for the final model using the original pr_df
final_model_df = pr_df[pr_df["Model_Type"] == "final"]

# Calculate AUPRC for training data
training_data = final_model_df[final_model_df["Data_Type"] == "training"]
training_auprc = auc(training_data["Recall"], training_data["Precision"])

# Calculate AUPRC for testing data
testing_data = final_model_df[final_model_df["Data_Type"] == "testing"]
testing_auprc = auc(testing_data["Recall"], testing_data["Precision"])

# Output the results
print(f"AUPRC for Training Data: {training_auprc:.4f}")
print(f"AUPRC for Testing Data: {testing_auprc:.4f}")

AUPRC for Training Data: 0.9616
AUPRC for Testing Data: 0.8917

### Plot precision-recall curves for holdout data per model type

In [7]:
# Custom colors for the holdout plot to differentiate between the training/testing plot
custom_colors = ["#0072B2", "#882255"]  # Blue, Burgundy

plt.figure(figsize=(12, 10))
sns.set_style("whitegrid")

# Filter data frame to only show holdout datasets
filtered_df = pr_df[pr_df["Data_Type"].isin(["holdout1", "holdout2"])]

sns.lineplot(
    x="Recall",
    y="Precision",
    hue="Data_Type",
    style="Model_Type",
    dashes={"final": (1, 0), "shuffled": (2, 2)},
    data=filtered_df,
    linewidth=4,  # Adjust the line width as needed
    palette=custom_colors  # Apply the custom color palette
)

plt.legend(loc="lower right", fontsize=13)
plt.ylim(bottom=0.0, top=1.02)
plt.xlabel("Recall", fontsize=18)
plt.ylabel("Precision", fontsize=18)
plt.title("Precision vs. Recall Plate 4 Holdout Datasets", fontsize=18)

# Adjust x-axis ticks font size
plt.xticks(fontsize=14)

# Adjust y-axis ticks font size and labels
plt.yticks(fontsize=14)

plt.tight_layout()
plt.savefig(f"{pr_curves_dir}/precision_recall_plate4_holdout_data_downsample.png", dpi=500)

# Close the plot to avoid showing it in the notebook
plt.close()

## Confusion Matrices

### Generate confusion matrix plots for each data set and model type

In [8]:
# Define the subdirectory for this plot type within fig_dir
con_matrix_dir = fig_dir / "confusion_matrices"
con_matrix_dir.mkdir(parents=True, exist_ok=True)  # Create subdirectory if it doesn't exist

# List of paths that contains each model
path_list = list(models_dir.glob("*"))

# List of data sets to apply models to
data_set_list = ["training", "testing", "holdout1", "holdout2"]

# Metadata column used for classifying
label = "Metadata_cell_type"

# Iterate over each model path
for model_path in path_list:
    if model_path.is_dir() or model_path.suffix != ".joblib":
        continue  # Skip directories or files that are not model files

    # Iterate over each dataset
    for data_set_name in data_set_list:
        print(
            "Generating plot for",
            data_set_name.capitalize(),
            model_path.stem.split("_")[5].capitalize(),
        )

        # Load dataset
        data_set_path = data_dir / f"{data_set_name}_data.csv"
        data_set = pd.read_csv(data_set_path)

        # If this is training data, filter rows using the training indices
        if data_set_path.stem == "training_data":
            # Skip the header row when reading the CSV
            training_indices = pd.read_csv(training_indices_path, header=0).iloc[:, 0].tolist()

            # Convert to integers to ensure compatibility
            try:
                training_indices = [int(idx) for idx in training_indices]
            except ValueError as e:
                print("Error parsing indices:", e)
                raise

            # Use .iloc if training_indices are row positions
            data_set = data_set.iloc[training_indices]

        # Generate confusion matrix data frame
        confusion_matrix_df = generate_confusion_matrix_df(
            model_path=model_path,
            data_df=data_set,
            encoder_path=encoder_path,
            label=label,
        )

        # Rename binary labels to failing versus healthy
        confusion_matrix_df["True_Label"] = confusion_matrix_df["True_Label"].replace({0: "Failing", 1: "Healthy"})
        confusion_matrix_df["Predicted_Label"] = confusion_matrix_df["Predicted_Label"].replace(
            {0: "Failing", 1: "Healthy"}
        )

        # Plot confusion matrix
        plt.figure(figsize=(12, 10))
        sns.set_style("whitegrid")

        heatmap = sns.heatmap(
            data=confusion_matrix_df.pivot(
                index="True_Label", columns="Predicted_Label", values="Recall"
            ),
            annot=confusion_matrix_df.pivot(
                index="True_Label", columns="Predicted_Label", values="Count"
            ),
            fmt=".0f",
            cmap="Reds",
            square=True,
            vmin=0,
            vmax=1,
            xticklabels=["Failing", "Healthy"],
            yticklabels=["Failing", "Healthy"],
            linewidths=0.5,
            annot_kws={"size": 16},  # Adjusted annotation font size
            mask=(
                confusion_matrix_df.pivot(
                    index="True_Label", columns="Predicted_Label", values="Count"
                ).isna()
            ),
            cbar_kws={"label": "Recall"},
        )

        # Adjust color bar label font size
        colorbar = heatmap.collections[0].colorbar
        colorbar.set_label("Recall", fontsize=14)  # Adjust colorbar label font size
        colorbar.ax.tick_params(labelsize=12)  # Adjust colorbar tick labels font size

        plt.title(
            f"Confusion Matrix for {data_set_name.capitalize()} Data - Model: {model_path.stem.split('_')[5].capitalize()}",
            fontsize=20,  # Adjusted title font size
        )
        plt.xticks(fontsize=14)  # Adjusted x-axis tick label font size
        plt.yticks(fontsize=14)  # Adjusted y-axis tick label font size
        plt.tight_layout()

        plt.savefig(
            f"{con_matrix_dir}/plate4_confusion_matrix_{data_set_name}_{model_path.stem.split('_')[5]}_downsample.png",
            dpi=500,
        )
        plt.close()

Generating plot for Training Final
Generating plot for Testing Final
Generating plot for Holdout1 Final

/tmp/ipykernel_4150415/1675443707.py:29: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set = pd.read_csv(data_set_path)

Generating plot for Holdout2 Final
Generating plot for Training Shuffled
Generating plot for Testing Shuffled
Generating plot for Holdout1 Shuffled

/tmp/ipykernel_4150415/1675443707.py:29: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set = pd.read_csv(data_set_path)

Generating plot for Holdout2 Shuffled

## F1 scores

### Concat F1 scores from all datasets and model types

In [9]:
# Define the subdirectory for this plot type within fig_dir
f1_scores_dir = fig_dir / "f1_scores"
f1_scores_dir.mkdir(parents=True, exist_ok=True)  # Create subdirectory if it doesn't exist

# List of paths that contains each model
path_list = list(models_dir.glob("*"))

# Metadata column used for classifying
label = "Metadata_cell_type"

# list for the f1 score dataframes per model and data split
f1_scores_dfs = []

# Iterate over each model path
for model_path in path_list:
    if model_path.is_dir() or model_path.suffix != ".joblib":
        continue  # Skip directories or files that are not model files
    
    # Iterate over each dataset
    for data_set_name in data_set_list:
        print(data_set_name.capitalize(), model_path.stem.split("_")[5].capitalize())

        # Load dataset
        data_set_path = data_dir / f"{data_set_name}_data.csv"
        data_set = pd.read_csv(data_set_path)

        # If this is training data, filter rows using the training indices
        if data_set_path.stem == "training_data":
            # Skip the header row when reading the CSV
            training_indices = pd.read_csv(training_indices_path, header=0).iloc[:, 0].tolist()

            # Convert to integers to ensure compatibility
            try:
                training_indices = [int(idx) for idx in training_indices]
            except ValueError as e:
                print("Error parsing indices:", e)
                raise

            # Use .iloc if training_indices are row positions
            data_set = data_set.iloc[training_indices]
        
        # Generate f1 score data frame
        f1_scores_df = generate_f1_score_df(
            model=model_path,
            data_set=data_set,
            encoder=encoder_path,
            label=label,
        )

        # Rename binary labels to failing versus healthy
        f1_scores_df = f1_scores_df.rename(columns={0: "Failing", 1: "Healthy"})

        # Add columns for model and data_set
        f1_scores_df["Model"] = model_path.stem.split("_")[5].capitalize()
        f1_scores_df["Data_Set"] = data_set_name.capitalize()

        # Append the DataFrame to the list
        f1_scores_dfs.append(f1_scores_df)

concat_f1_scores = pd.concat(f1_scores_dfs, ignore_index=True)

Training Final
Testing Final
Holdout1 Final

/tmp/ipykernel_4150415/1895714963.py:25: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set = pd.read_csv(data_set_path)

Holdout2 Final
Training Shuffled
Testing Shuffled
Holdout1 Shuffled
Holdout2 Shuffled

/tmp/ipykernel_4150415/1895714963.py:25: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set = pd.read_csv(data_set_path)

### Check if output looks correct

In [10]:
print(concat_f1_scores.shape)
concat_f1_scores.head()

(8, 5)

    Failing   Healthy  Weighted     Model  Data_Set
0  0.912069  0.912636  0.912353     Final  Training
1  0.898067  0.838777  0.875867     Final   Testing
2  0.881365  0.786213  0.851662     Final  Holdout1
3  0.898096  0.842014  0.877213     Final  Holdout2
4  0.540962  0.514032  0.527497  Shuffled  Training

### Plot F1 scores for only testing and training data

In [11]:
# Set palette for the F1 scores plot
palette = sns.color_palette("Paired")[:2]

# Set figure size
plt.figure(figsize=(10, 6))

# Set y-axis limits
plt.ylim(0, 1)

# Filter the data to include only training and testing sets
filtered_data = concat_f1_scores[
    concat_f1_scores["Data_Set"].isin(["Training", "Testing"])
]

ax = sns.barplot(
    x="Model", y="Weighted", hue="Data_Set", data=filtered_data, palette=palette
)

# Add horizontal grid lines
ax.yaxis.grid(True, color="gray", linestyle="--", linewidth=0.7, alpha=0.7)
ax.set_axisbelow(True)  # Ensure grid lines are below the bars

# Add the weighted values above the bars
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(
            f"{height:.2f}",
            (p.get_x() + p.get_width() / 2.0, height),
            ha="center",
            va="center",
            xytext=(0, 10),
            textcoords="offset points",
        )

plt.title("Weighted F1 Score by Model Type")
plt.xlabel("Model Type")
plt.ylabel("Weighted F1 Score")
plt.legend(title="Data Set")
plt.tight_layout()

plt.savefig(f"{f1_scores_dir}/f1_scores_plate4_downsample.png", dpi=500)

# Avoid showing plot in the notebook
plt.close()

### Plot F1 scores for holdout data

In [12]:
# Set palette for the f1 scores plot
palette = sns.color_palette("Paired")[2:4]

# Set figure size
plt.figure(figsize=(10, 6))

# Set y-axis limits
plt.ylim(0, 1)

# Filter the data to include only hold-out sets
filtered_data = concat_f1_scores[
    concat_f1_scores["Data_Set"].isin(["Holdout1", "Holdout2"])
]

ax = sns.barplot(
    x="Model", y="Weighted", hue="Data_Set", data=filtered_data, palette=palette
)

# Add the weighted values above the bars
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(
            f"{height:.2f}",
            (p.get_x() + p.get_width() / 2.0, height),
            ha="center",
            va="center",
            xytext=(0, 10),
            textcoords="offset points",
        )

plt.title("Weighted F1 Score by Model Type")
plt.xlabel("Model Type")
plt.ylabel("Weighted F1 Score")
plt.legend(title="Data Set")
plt.tight_layout()

plt.savefig(f"{f1_scores_dir}/f1_scores_plate4_holdout_data_downsample.png", dpi=500)

# Avoid showing plot in the notebook
plt.close()

## Generate accuracy scores specifically from the whole plate 4 dataset per heart and save CSV

In [13]:
# List of paths that contains each model
path_list = list(models_dir.glob("*"))

# Metadata column used for classifying
label = "Metadata_cell_type"

# List for all accuracy dataframes for concat
accuracy_dfs = []

# Iterate over each model path
for model_path in path_list:
    if model_path.is_dir() or model_path.suffix != ".joblib":
        continue  # Skip directories or files that are not model files
    # Iterate over each dataset
    for data_set in data_set_list:
        print(data_set.capitalize(), model_path.stem.split("_")[5].capitalize())

        # Load the dataset
        data_path = data_dir / f"{data_set}_data.csv"
        data_df = pd.read_csv(data_path)

        # If this is training data, filter rows using the training indices
        if data_set == "training":
            # Skip the header row when reading the CSV
            training_indices = pd.read_csv(training_indices_path, header=0).iloc[:, 0].tolist()

            # Convert to integers to ensure compatibility
            try:
                training_indices = [int(idx) for idx in training_indices]
            except ValueError as e:
                print("Error parsing indices:", e)
                raise

            # Use .iloc if training_indices are row positions
            data_df = data_df.iloc[training_indices]

        # Group the data by heart number
        grouped_data = data_df.groupby("Metadata_heart_number")

        # Iterate over each group (heart number)
        for heart_number, df_heart in grouped_data:
            # Generate accuracy data frame
            accuracy_df = generate_accuracy_score_df(
                model=model_path,
                data_set=df_heart,
                encoder=encoder_path,
                label=label,
            )

            # Rename binary labels to failing versus healthy
            accuracy_df = accuracy_df.rename(columns={0: "Failing", 1: "Healthy"})

            # Add columns for model, data_set, and heart number
            accuracy_df["Model"] = model_path.stem.split("_")[5].capitalize()
            accuracy_df["Data_Set"] = data_set.capitalize()
            accuracy_df["Heart_Number"] = heart_number

            # Append the DataFrame to the list
            accuracy_dfs.append(accuracy_df)

# Merge all of the accuracy scores across model type and data splot
concat_accuracy_scores = pd.concat(accuracy_dfs, ignore_index=True)

# Save results for visualization
concat_accuracy_scores.to_csv(f"{results_dir}/accuracy_scores_per_heart.csv", index=False)

Training Final
Testing Final
Holdout1 Final

/tmp/ipykernel_4150415/1097586815.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df = pd.read_csv(data_path)

Holdout2 Final
Training Shuffled
Testing Shuffled
Holdout1 Shuffled
Holdout2 Shuffled

/tmp/ipykernel_4150415/1097586815.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df = pd.read_csv(data_path)